### PR TITLE
MOVER-delivery: DO NOT MERGE

### PR DESCRIPTION
**Pull request by vezzi**
This is a working prototype of taca delivery grus.
The delivery will happen in the following three steps:

1. `taca -c delivery.yml deliver  --ignore-analysis-status --stage_only project P6968`
2. `taca -c delivery.yml deliver --cluster grus  project P6968`
3. `taca -c sthlm_taca_fastq_delivery.yml deliver check_status P6968`

The first command makes a soft stage of the project. All project or individual samples can be specified. Some of the new features are:

 - Only sample with status `STALE` can be soft-staged. This can be over-written by `--force` but in general, form now on, `--force` should be avoided. 
 - If WHG has not been run, then `--ignore-analysis-status` will allow to deliver samples anyway
 - samples will be marked as `STAGED` on charon.

Second command is responsible to deliver data to grus. Collects all `STAGED` samples, performs hard-staging (i.e., defers softlinks), retrieves from statusdb pi-email, creates delivery project via snic-api, and calls to_mover. Features:
 
 - statusDB config is expected in env variable `STATUS_DB_CONFIG` (untested on Irma)
 - SNIC-API credentials are expected in env variable `SNIC_API_STOCKHOLM`  (untested on Irma)
 - for now retrieves PI-mail and then overwrites it with mine
 - stores delivery-token produced by `to_mover` in charon project field.
 - for a given project on charon, only one delivery is possible (delivery token is used to check this).

In general we should do a single deliver. To perform multiple deliveries one needs first to softstage or re-softstage samples, and then redeliver.

The last command is supposed to be run straight after the second. It starts a while loop. Every minute (for now, it will become every 15 minutes) checks the status of the delivery via mover_info. It returns only when status of delivery is ACCEPTED or when it timed out. In case status returned by `moverinfo` is FAILED, it prints a warning but it does not fail. It is up to the bioinformatician to understand if there is some serious problem. 

**This last command has been tested to completion only once.**

Special mention to @kate-v-stepanova that wrote the backbone of the code and the main logic behind!!!

### CODE REVIEW

**Comment by vezzi** [comment]
Hi guys, the plan was to be done with this today but internet problems, irma down for maintenance and me being sick had delayed things a bit....
I still need to perform some test on this but it is in main part ready. I would like you three to have a look at is and check that the changes I made to taca-ngi-pipeline do not interfere with the current operations. I think that this code can be easily be merged without creating troubles. In the next days I will run some tests and implement suggestions or changes coming from you

**Comment by vezzi** [comment]
@sylvinite this is now almost done, I have tested it extensively and wrote documentation in AM. Can you please review the code and check for problems in the logic? thanks

**Comment by vezzi** [comment]
@SciLifeLab/collaborators wait for merge as I might need to do a couple of more push

**Comment by sylvinite** [comment]
Small thing I picked up:

- Travis fixes can be removed, as the issue is now fixed in TACA directly.
- --ignore-analysis-status could use a short version as it is used frequently
- The error _--statusdb-config or env variable $STATUS_DB_CONFIG need to be set to perform GRUS delivery_ should be used regardless of cluster destination.
- Line breaks for if cases is a bit odd when the proceeding logging line doesn't have it.

For the code itself I see no obvious logical issues. Solid stuff.

**Comment by vezzi** [comment]
DONE. @sylvinite please give an other look and then we can merge

**Pull request merged**
