### PR TITLE
Add option to generate xml and manifest files by themselves

### PR DESCRIPTION
**Pull request by aanil**

### CODE REVIEW

**Comment by ssjunnebo** [comment]
Looks good to me except that the tests are failing. Seems to be an issue with traitlets not supporting python2 anymore?

**Comment by aanil** [comment]
Fixed the issue with traitlets on travis!

**Review by ssjunnebo — APPROVED** [review]
👍

**Comment by alneberg** [comment]
@aanil and @ssjunnebo, feel free to merge this as you wish. I trust you.

**Pull request merged**
