### PR TITLE
Port to python 3

### PR DESCRIPTION
**Pull request by ssjunnebo**
Should now be compatible with both python 2.7 and 3 🎉 

I'm pretty sure the order in the list returned by the [merge_dicts](https://github.com/ssjunnebo/taca-ngi-pipeline/blob/5ff8a884961555deaee314f915be9092c041bd4c/taca_ngi_pipeline/utils/filesystem.py#L138) function does not matter. It differed between the python versions so I decided to sort it. Please correct me if I'm wrong or you think of a better way to fix this! 🙂

### CODE REVIEW

**Comment by alneberg** [comment]
Awesome! I havne't dealt with this code at all (I think) so hard for me to test it. I think it looks good though, so I would be happy to approve it when thats appropriate (now or after the validation?). I think sorting the list from the dict makes sense, I think python3 keeps dictionaries sorted, while python2 doesn't so it's not strange that it happens.

**Comment by ssjunnebo** [comment]
> Awesome! I havne't dealt with this code at all (I think) so hard for me to test it. I think it looks good though, so I would be happy to approve it when thats appropriate (now or after the validation?). I think sorting the list from the dict makes sense, I think python3 keeps dictionaries sorted, while python2 doesn't so it's not strange that it happens.

Nice 🙂 I've managed to run a staging, delivery and monitoring on irma without any issues. I think we'll do the validation during the deployment 👍

**Review by aanil — APPROVED** [review]
The changes look ok to me!

**Review by alneberg — APPROVED** [review]
👍

**Pull request merged**
